name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'etc/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        emacs_version:
          - "26.1"
          - "26.3"
          - "27.1"
          - "27.2"
          - "28.1"
          - "28.2"
          - "29.1"
          - release-snapshot
          - snapshot
        include:
          - emacs_version: snapshot
            allow_failure: true
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master
      with:
        version: 'snapshot'
    - uses: actions/checkout@v3
    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make test'
    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make test || true'
